replicaCount: 1

image:
  registry: ""
  repository: calendar-sender
  tag: "latest"
  pullPolicy: Never

config:
  rabbit:
    connectionString: "amqp://guest:guest@rabbitmq:5672/"
    queue: "queue"
  logging:
    level: DEBUG
  db:
    inMemory: false
    host: postgres
    port: 5432
    user: postgres
    password: postgres
    dbname: calendar
    schema: public