rabbit:
  connection-string: "amqp://guest:guest@localhost:5672/"
  queue: "queue"

db:
  in-memory: false
  host: localhost
  port: 5432
  user: postgres
  dbname: postgres
  tables:
    schema: public

logging:
  level: DEBUG