logging:
  level: info

server:
  http-host: 0.0.0.0
  http-port: 8080
  grpc-host: 0.0.0.0
  grpc-port: 50051

db:
  in-memory: false
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: calendar
  tables:
    schema: public
