rabbit:
  connection-string: "amqp://guest:guest@rabbitmq:5672/"
  queue: "queue"

db:
  in-memory: false
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: calendar
  tables:
    schema: public

logging:
  level: DEBUG