logging:
  level: info

server:
  http-host: localhost
  http-port: 8080
  grpc-host: localhost
  grpc-port: 50051

db:
  in-memory: false
  host: localhost
  port: 5432
  user: postgres
  dbname: postgres
  tables:
    schema: public
