logging:
  level: info

server:
  port: 8080
  host: localhost
  mode: release

db:
  in-memory: false
  host: localhost
  port: 5432
  user: postgres
  dbname: postgres
  tables:
    schema: public
    events: events
